/**
 * Self-serve onboarding — Blok 3.1.
 *
 * Square OAuth (see lib/squareOauth.ts + routes/onboarding.ts /square/start
 * and /square/callback) is REAL — the restaurant authorizes Square
 * themselves and Orderly stores encrypted tokens, never plaintext creds.
 * Everything else here is intentionally still a skeleton:
 *  - "Theme" is a deterministic name-hash → palette lookup (a stub), not ML.
 *  - menu-draft is stored as opaque JSON and never written to the live
 *    menu_categories / menu_items tables.
 *  - /publish is hard-gated behind ONBOARDING_PUBLISH_ENABLED=1 and, even
 *    then, only ever creates an inactive/draft tenants row (never "active",
 *    never touches money/payment config) — a human must still promote it.
 */
import { randomUUID, createHash } from "crypto";
import { db, onboardingSessionsTable, tenantsTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import type { OnboardingSession } from "@workspace/db";
import { linkSquareOauthConnectionToTenant } from "./squareOauth";

export const ONBOARDING_STATUSES = [
  "draft",
  "theme_set",
  "variant_set",
  "menu_draft",
  "domain_set",
  "ready",
  "published",
] as const;
export type OnboardingStatus = (typeof ONBOARDING_STATUSES)[number];

export const ONBOARDING_VARIANTS = ["classic", "modern", "minimal"] as const;
export type OnboardingVariant = (typeof ONBOARDING_VARIANTS)[number];

/**
 * Small fixed palette set — NOT generated by any model. Deterministic pick
 * keyed on a hash of the restaurant name so the same name always renders the
 * same stub theme (useful for demos + tests).
 */
const STUB_PALETTES: Array<{
  key: string;
  primary: string;
  accent: string;
}> = [
  { key: "ember", primary: "354 82% 50%", accent: "43 74% 49%" },
  { key: "sage", primary: "142 45% 36%", accent: "40 60% 55%" },
  { key: "ocean", primary: "205 70% 42%", accent: "190 55% 60%" },
  { key: "plum", primary: "280 45% 45%", accent: "330 55% 60%" },
  { key: "citrus", primary: "28 85% 50%", accent: "50 90% 55%" },
  { key: "slate", primary: "215 20% 35%", accent: "205 30% 55%" },
];

function nameHashInt(name: string): number {
  const hex = createHash("sha256").update(name.trim().toLowerCase()).digest("hex");
  return parseInt(hex.slice(0, 8), 16);
}

/** Stub auto theme — deterministic palette-from-name-hash, not ML. */
export function generateStubTheme(
  restaurantName: string,
  logoUrl?: string | null,
): Record<string, unknown> {
  const idx = nameHashInt(restaurantName) % STUB_PALETTES.length;
  const palette = STUB_PALETTES[idx];
  return {
    method: "stub_name_hash",
    paletteKey: palette.key,
    primary: palette.primary,
    accent: palette.accent,
    logoUrl: logoUrl?.trim() || null,
    brandName: restaurantName,
  };
}

export interface StartOnboardingInput {
  restaurantName: string;
  address?: string | null;
  contact?: Record<string, unknown> | null;
  cuisine?: string | null;
}

function toPublic(row: OnboardingSession) {
  return {
    id: row.id,
    status: row.status,
    restaurantName: row.restaurantName,
    address: row.address,
    contact: row.contact,
    cuisine: row.cuisine,
    theme: row.theme,
    variant: row.variant,
    menuDraft: row.menuDraft,
    domain: row.domain,
    square: {
      connected: Boolean(row.squareMerchantId && row.squareLocationId),
      merchantId: row.squareMerchantId,
      locationId: row.squareLocationId,
      connectedAt: row.squareConnectedAt,
    },
    // squareOauthState intentionally omitted from public payloads (CSRF token).
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

export type PublicOnboardingSession = ReturnType<typeof toPublic>;

export async function createOnboardingSession(
  input: StartOnboardingInput,
): Promise<PublicOnboardingSession> {
  const id = randomUUID();
  const now = new Date();
  await db.insert(onboardingSessionsTable).values({
    id,
    status: "draft",
    restaurantName: input.restaurantName.trim(),
    address: input.address?.trim() || null,
    contact: input.contact ?? {},
    cuisine: input.cuisine?.trim() || null,
    theme: {},
    variant: null,
    menuDraft: {},
    domain: null,
    squareOauthState: null,
    createdAt: now,
    updatedAt: now,
  });
  const row = await getOnboardingSessionRow(id);
  return toPublic(row!);
}

export async function getOnboardingSessionRow(
  id: string,
): Promise<OnboardingSession | null> {
  if (!id) return null;
  const rows = await db
    .select()
    .from(onboardingSessionsTable)
    .where(eq(onboardingSessionsTable.id, id))
    .limit(1);
  return rows[0] ?? null;
}

export async function getOnboardingSessionPublic(
  id: string,
): Promise<PublicOnboardingSession | null> {
  const row = await getOnboardingSessionRow(id);
  return row ? toPublic(row) : null;
}

async function patchSession(
  id: string,
  patch: Partial<typeof onboardingSessionsTable.$inferInsert>,
): Promise<PublicOnboardingSession | null> {
  const existing = await getOnboardingSessionRow(id);
  if (!existing) return null;
  await db
    .update(onboardingSessionsTable)
    .set({ ...patch, updatedAt: new Date() })
    .where(eq(onboardingSessionsTable.id, id));
  const row = await getOnboardingSessionRow(id);
  return row ? toPublic(row) : null;
}

export async function setSessionTheme(
  id: string,
  logoUrl?: string | null,
): Promise<PublicOnboardingSession | null> {
  const existing = await getOnboardingSessionRow(id);
  if (!existing) return null;
  const theme = generateStubTheme(existing.restaurantName, logoUrl);
  return patchSession(id, { theme, status: "theme_set" });
}

export async function setSessionVariant(
  id: string,
  variant: string,
): Promise<PublicOnboardingSession | null> {
  return patchSession(id, { variant, status: "variant_set" });
}

export async function setSessionMenuDraft(
  id: string,
  items: unknown[],
): Promise<PublicOnboardingSession | null> {
  return patchSession(id, {
    menuDraft: { items, itemCount: items.length, savedAt: new Date().toISOString() },
    status: "menu_draft",
  });
}

export async function setSessionDomain(
  id: string,
  domain: string,
): Promise<PublicOnboardingSession | null> {
  return patchSession(id, { domain, status: "domain_set" });
}

export async function setSessionSquareOauthState(
  id: string,
  state: string,
): Promise<void> {
  await patchSession(id, { squareOauthState: state });
}

/**
 * Looks up the onboarding session that started the OAuth flow with this CSRF
 * state. Used by /square/callback, which only receives ?state= (not the
 * session id) — Square doesn't round-trip arbitrary extra params reliably.
 */
export async function findOnboardingSessionByOauthState(
  state: string,
): Promise<OnboardingSession | null> {
  if (!state) return null;
  const rows = await db
    .select()
    .from(onboardingSessionsTable)
    .where(eq(onboardingSessionsTable.squareOauthState, state))
    .limit(1);
  return rows[0] ?? null;
}

/**
 * Marks a session Square-connected and burns the CSRF state so it cannot be
 * replayed against /square/callback a second time.
 */
export async function markSessionSquareConnected(
  id: string,
  merchantId: string,
  locationId: string,
): Promise<PublicOnboardingSession | null> {
  return patchSession(id, {
    squareOauthState: null,
    squareMerchantId: merchantId,
    squareLocationId: locationId,
    squareConnectedAt: new Date(),
  });
}

export async function markSessionPublished(id: string): Promise<void> {
  await patchSession(id, { status: "published" });
}

/**
 * Gated, skeleton-only tenant creation. Never sets status "active" — a human
 * must flip that later through the normal tenant admin path. This function
 * is only reachable from the /publish route when
 * ONBOARDING_PUBLISH_ENABLED=1.
 */
export async function publishDraftTenantShell(
  session: OnboardingSession,
): Promise<{ tenantId: string }> {
  const slugBase = session.restaurantName
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
  const slug = slugBase || `restaurant-${session.id.slice(0, 8)}`;
  const tenantId = `onboarding-${session.id}`;
  const theme = (session.theme as Record<string, unknown>) || {};
  const domain =
    session.domain?.trim() || `${slug}.onboarding.orderlyfoods.internal`;

  await db.insert(tenantsTable).values({
    id: tenantId,
    slug,
    name: session.restaurantName,
    domain,
    logoUrl: (theme.logoUrl as string | null) ?? null,
    theme,
    address: session.address,
    lat: 0,
    lng: 0,
    posType: "square",
    dataMode: "pos-full",
    // Never active from self-serve skeleton — a human must promote this.
    status: "draft",
  });

  // Real Square OAuth connection (if the restaurant connected it) — link it to
  // the new tenant row so integrations/square.ts can resolve tokens by
  // tenant once a human flips status to "active". No tokens are ever written
  // to git/ecosystem.config here; this only updates the existing encrypted
  // DB row's tenant_id.
  if (session.squareMerchantId && session.squareLocationId) {
    await linkSquareOauthConnectionToTenant(session.id, tenantId);
  }

  return { tenantId };
}
